---
- name: "APT: Install dependencies"
  ansible.builtin.apt:
    pkg:
      - "squid"
    state: present
  when: ansible_os_family == 'Debian'

- name: "DNF: Install dependencies"
  ansible.builtin.dnf:
    name:
      - "squid"
    state: present
  when: ansible_os_family == 'RedHat'

- name: "Determine mount for /var/spool/squid"
  shell: "findmnt --target /var/spool/squid | tail -n +2 | awk '{ print $1 };'"
  register: squid_mount
  changed_when: false
  failed_when: squid_mount.rc != 0 or squid_mount.stdout | length == 0

- name: "Determine squid volume size in GB"
  set_fact:
    squid_volume_size: "{{ (ansible_mounts | selectattr('mount', 'equalto', squid_mount.stdout) | list | first).size_total // (1024 * 1024 * 1024) }}"

- name: "Write squid configuration"
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: "root"
    group: "squid"
    mode: "640"
  notify: restart_squid

- name: "UFW: enable port"
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 8080
  when: ansible_os_family == 'Debian'

- name: "FirewallD: enable port"
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}/tcp"
    state: enabled
  with_items:
    - 8080
  when: ansible_os_family == 'RedHat'

- name: "Ensure squid is enabled and started"
  service:
    name: squid
    state: started
    enabled: yes
